name: Building Wine 7z Package
run-name: ${{ github.actor }} Building Wine 7z Package 🚀
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Building Wine
        env: 
          GUSER: ${{ secrets.GUSER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          UPLOADURL: ${{ secrets.UPLOADURL }}
        run: |
          # 配置编译容器
          sudo apt update
          sudo apt install aria2 debootstrap neofetch python3 curl -y
          neofetch
          sudo debootstrap --arch amd64 buster ~/debian10-amd64
          sudo aria2c -d /usr/bin -o pardus-chroot https://github.com/gfdgd-xi/deep-wine-runner/raw/main/pardus-chroot
          sudo chmod 777 /usr/bin/pardus-chroot
          sudo pardus-chroot ~/debian10-amd64
          # 编译 amd64 wine
          sudo aria2c -d ~/debian10-amd64 -o wineautobuild-action-7z.sh https://github.com/gfdgd-xi/deep-wine-runner/raw/main/wineautobuild-action-7z.sh
          git clone https://github.com/gfdgd-xi/auto-building-wine --depth=1
          sudo cp auto-building-wine/wine-version.txt ~/debian10-amd64 -rv
          sudo cp auto-building-wine/wine-url.txt ~/debian10-amd64 -rv
          sudo cp auto-building-wine/wine-type.txt ~/debian10-amd64 -rv
          sudo chroot ~/debian10-amd64 bash /wineautobuild-action-7z.sh
          # 提交wine
          # 获取数据
          url=`cat auto-building-wine/wine-url.txt`
          version=`cat auto-building-wine/wine-version.txt`
          type=`cat auto-building-wine/wine-type.txt`
          #curl -F "file=@$HOME/debian10-amd64/wine/wine-$type-$version-debian10-amd64.7z" "$UPLOADURL"
          #curl -F "file=@$HOME/debian10-amd64/wine/wine-$type-$version-debian10-x86_64.7z" "$UPLOADURL"
          #curl -F "file=@$HOME/debian10-amd64/wine/wine-$type-$version-debian10-i386.7z" "$UPLOADURL"
          sudo mv $HOME/debian10-amd64/wine/wine-$type-$version-debian10-amd64.7z   ~/wine-amd64.7z
          sudo mv $HOME/debian10-amd64/wine/wine-$type-$version-debian10-x86_64.7z  ~/wine-x86_64.7z
          sudo mv $HOME/debian10-amd64/wine/wine-$type-$version-debian10-i386.7z    ~/wine-i386.7z
      - name: upload result(Wine AMD64)
        uses: actions/upload-artifact@v2
        with:
          name: wine-debian10-amd64
          path: /home/runner/wine-amd64.7z
      - name: upload result(Wine I386)
        uses: actions/upload-artifact@v2
        with:
          name: wine-debian10-i386
          path: /home/runner/wine-i386.7z
      - name: upload result(Wine X86_64)
        uses: actions/upload-artifact@v2
        with:
          name: wine-debian10-x86_64
          path: /home/runner/wine-x86_64.7z
      